In [1]:
import numpy as np

In [2]:
# Arthimatic opertions 

In [3]:
# sin , cos , tan
#  (degree)وليس (radians)الدوال المثلثيةتتعامل بال 

# degree  >> 90   180 270 360
# radians >>     

In [4]:
# radincs
a = np.sin(30)
b = np.cos(30)
c = np.tan(30)
print(a , b , c)

-0.9880316240928618 0.15425144988758405 -6.405331196646276


In [5]:
# convert from radincs to degree 
a = np.sin(30 * np.pi/180)
b = np.cos(30 * np.pi/180)
c = np.tan(30 * np.pi/180)
print(a , b , c)


0.49999999999999994 0.8660254037844387 0.5773502691896257


In [6]:
# convert from radincs to degree 
a = np.sin(np.deg2rad(30))
b = np.cos(np.deg2rad(30))
c = np.tan(np.deg2rad(30))
print(a , b , c)


0.49999999999999994 0.8660254037844387 0.5773502691896257


In [7]:
# round
 
a = np.round(3.6711)
b = np.round(3.6711 , 1)
c = np.round(3.6711 , 2)
d = np.round(3.6711 , 3)
print(a ,b , c ,d)

4.0 3.7 3.67 3.671


In [8]:
# floor & ceil
a = np.floor(3.658)
b = np.ceil(3.658)

print(a , b)

3.0 4.0


In [9]:
# mod 

a = np.mod(20 , 7)
print(a)


6


In [10]:
# power 
a = np.power(2 , 5)
print(a)

32


In [14]:
# matrices 

l = [2 , 3,  4 , 5 , 6]
m = np.array(l) 
print(l)
print(m)
print(type(m))

[2, 3, 4, 5, 6]
[2 3 4 5 6]
<class 'numpy.ndarray'>


In [16]:
l = [[1,2,3] , [5 , 3 ,6 ] , [9 ,6 ,5]]
m = np.array(l)
print(m)

[[1 2 3]
 [5 3 6]
 [9 6 5]]


In [17]:
m = np.array([range(i ,i +3) for i in [2 ,4 ,6]])
print(m) 

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [18]:
m = np.array([('x' , 3 , 4 ) , ('y' , 6 , 3) , ('z' , 7 ,3 )] , 
             dtype = [('name' , 'U5') , ('number' , 'i2') , ('value' , 'f4')] )
print(m)

[('x', 3, 4.) ('y', 6, 3.) ('z', 7, 3.)]


In [20]:
m = np.empty((2 , 3))
print(m)

[[9.34577196e-307 9.34598246e-307 1.60218491e-306]
 [1.69119873e-306 1.24611673e-306 1.00136897e-307]]


In [21]:
a = np.random.uniform(1 , 10) # one num between 1 and 10 
b = np.random.uniform(1 ,10, 20) # 20 num between 1 and 10 
m = np.array(b)
print(a) 
print("......................................")
print(m) 

1.605810014935139
......................................
[4.06578416 1.17718099 5.6073816  4.12706744 2.79776791 4.02946757
 4.55919058 6.96180755 2.0695061  9.91885528 9.7363994  3.76817299
 8.70059727 9.20654928 9.64963438 7.66692798 8.11154525 6.09843039
 5.48823647 4.63771747]


In [24]:
m = np.random.random((2 , 3)) # matrices 2 x 3 have randoms values 0 : 1
print(m)

[[0.83820874 0.0680045  0.85659273]
 [0.77891568 0.05268442 0.82877847]]


In [25]:
m = np.random.random((2 , 3)) * 10 # matrices 2 x 3 have randoms values 0 : 10
print(m)

[[6.72635575 8.01928116 0.99464442]
 [3.32110392 4.88882694 4.97378728]]


In [28]:
m = np.random.normal(0 , 1 , 10)
print(m) 

[-0.42042604  0.79956887 -0.27648907 -1.26500726 -0.42908545  0.66165184
  1.61952887 -0.57077716 -0.32956564 -0.02802145]


In [29]:
a = np.random.randint(140)
m = np.random.randint(5 , size=7)       # 7 randoms int nums   0 : 5 
m2 = np.random.randint(5 ,10 , size=7)  # 7 randoms int nums   5 : 10 

print(a)
print("......................................")
print(m)
print("......................................")
print(m2)


130
......................................
[4 0 1 4 1 1 4]
......................................
[8 8 8 9 8 8 7]


In [30]:
m = np.random.randint(5 ,10 , (3 , 2))
print(m)

[[9 7]
 [8 9]
 [8 9]]


In [31]:
m = np.random.randint(5 ,10 , (3 , 2 , 2))
print(m) 

[[[5 6]
  [9 6]]

 [[7 9]
  [9 6]]

 [[9 9]
  [8 9]]]


In [34]:
m = np.random.randint(1 ,50 , 25)
m = np.reshape(m , (5 , 5))
print(m)

[[41 33  8 34  8]
 [30 43 38 26 30]
 [17 14 43  5  3]
 [28 37 21 31 24]
 [ 3 46  5 12 25]]
